ボタン機能とモーター駆動機能の追加
armonica-IVRC2023/armonica-sensor pull request #2
Opened 2023-08-07 22:28 UTC by ikigyihi

2023-08-10 11:30 UTC, ikigyihi commented on read_analog/read_analog.ino
> -// 必要なライブラリをインクルード
test

2023-08-10 13:07 UTC, norm-ideal requested changes

2023-08-10 13:07 UTC, norm-ideal commented on read_analog/read_analog.ino
> +  if (Serial.available() > 0){
せっかくだから、２２〜２７行目のシリアル送信部も、このチェックの中に入れてください。

2023-08-10 13:07 UTC, norm-ideal commented on read_analog/read_analog.ino
> +      }else if(data == "1"){
ここ、字が下がりすぎです。`if` と同じ高さに。

2023-08-10 13:07 UTC, norm-ideal commented on read_analog/read_analog.ino
> +      }else if(data == "1"){
このあとのブロックも、凸凹しているので修正をよろしく！

2023-08-10 15:21 UTC, norm-ideal commented on read_analog/read_analog.ino
> +      }else if(data == "1"){
`if` の中、`else if` の中は字下げしてください。よろしく！

C 系では字下げなしでも動いてしまいますが、ブロックを字下げで表現するのは Python と一緒です。

2023-08-10 15:24 UTC, norm-ideal commented on read_analog/read_analog.ino
> +    digitalWrite(motorPin5,LOW);
ここの行と、下の `else` 節の行は、字下げしてください〜　C 系だと動いてしまいますが、字下げでブロックを表します。python が「ちゃんと字下げしないと動かない」ことを理由として、導入教育用に適していると言われています。

2023-08-10 15:24 UTC, norm-ideal commented on read_analog/read_analog.ino
> +  if (Serial.available() > 0){
こっちは未修正の方のコメントです。もう一回開きます。よろしく。

2023-08-11 06:29 UTC, norm-ideal commented
ありがとう！　入力電圧の謎は、実機がないとどうしようもないのでこれでひとまず終了です。 @Yoshiaki010 と合流して、送受信部分 

https://github.com/armonica-IVRC2023/armonica01/blob/main/armonica01/Assets/Scenes/Kazushi/SerialController.cs

2023-08-11 06:29 UTC, merged

2023-08-13 05:31 UTC, Yoshiaki010 commented
SerialControllerの開発場所見つけた！